---
- name: download waf executable
  get_url: >
    url={{waf_url}}
    dest=/usr/local/bin/{{waf_exe}}
    mode=0755
  
- name: link waf
  file: src='/usr/local/bin/{{waf_exe}}' dest=/usr/local/bin/waf state=link

- name: seed waf
  command: /usr/local/bin/waf --version