---
- name: downloading {{ waf_url }}
  become: yes
  become_user: root
  get_url:
    url: '{{ waf_url }}'
    dest: '{{ waf_installed_exe }}'
    checksum: '{{ waf_checksum }}'
    mode: 0755
  
- name: linking {{ waf_installed_exe }} to {{ waf_installed_link }}
  become: yes
  become_user: root
  file:
    src: '{{ waf_installed_exe }}'
    dest: '{{ waf_installed_link }}'
    state: link

- name: seed {{ waf_installed_exe }}
  become: yes
  become_user: root
  command: '{{ waf_installed_exe }} configure'
